[dataCard] with text or gauge percentage
dataesr/bso-ui pull request #40
Opened 2021-06-11 14:50 UTC by francasix

2021-06-14 09:50 UTC, annelhote commented on src/components/charts/publications/general/charts-dynamique-ouverture/get-data.js
> +    const res = await Axios.post(ES_API_URL, query, HEADERS);
Non je pense que le catch est utile ici ! Pour désactiver le warning, plutôt ajouter un "/* eslint-disable no-console */" au tête de ce fichier.

2021-06-14 09:52 UTC, annelhote requested changes

2021-06-14 09:52 UTC, annelhote commented on .eslintrc.json
> +    "react/prop-types": "warn",
Pourquoi supprimer ce warning ? C'est généralement une bonne pratique de ne pas avoir des lignes trop longues ? Peut-être le passer à 150 si tu veux...

2021-06-14 17:20 UTC, francasix commented on .eslintrc.json
> +    "react/prop-types": "warn",
J'avais 3 millions d'erreurs, je sais pas comment vous ne les aviez pas aussi ?

2021-06-15 06:21 UTC, francasix commented on .eslintrc.json
> +    "react/prop-types": "warn",
J'ai mis _200_ et raccourci les string Lorem ipsum trop longs.

2021-06-15 13:38 UTC, annelhote approved these changes

2021-06-15 13:50 UTC, merged