i18n + structure graphs
dataesr/bso-ui pull request #43
Opened 2021-06-15 15:33 UTC by jerem1508

2021-06-15 16:46 UTC, francasix requested changes
Fix conflicts et merge pour review

2021-06-15 16:46 UTC, francasix commented on .eslintrc.json
> +  "extends": [
on a déjà ces extends dans staging

2021-06-16 13:30 UTC, annelhote requested changes

2021-06-16 13:30 UTC, annelhote commented on src/components/charts/publications/general/voies-ouverture/get-data.js
> +/* eslint-disable no-console */
Plus nécessaire je pense

2021-06-16 13:31 UTC, annelhote commented on .eslintrc.json
> +  "extends": [
J'ai l'impression qu'il y a eu un merge de staging dans cette branche.

2021-06-18 08:53 UTC, jerem1508 commented
abandon car sur main

2021-06-18 08:53 UTC, closed without merging